[services.backend]
name = "backend"
buildCommand = "cd server && npm install"
startCommand = "cd server && node server.js"
env = [
  "MONGO_URI",
  "JWT_SECRET",
  "PORT",
  "NODE_ENV",
  "JWT_EXPIRE"
]

[services.frontend]
name = "frontend"
buildCommand = "cd client && npm install && npm run build"
startCommand = "cd client && npm start"
env = [
  "NEXT_PUBLIC_API_URL"
]

[env]
MONGO_URI = "mongodb+srv://diope2diope:3IpTZ6hGwXkEdgm7@cluster0.poyyb0c.mongodb.net/icyizere?retryWrites=true&w=majority"
JWT_SECRET = "H8J2n4k6m8N0p2R4t6V8x0Z2b4d6F8h0J2l4N6p8R0t2v4X6z8B0D2f4"
JWT_EXPIRE = "30d"
JWT_COOKIE_EXPIRE = "30"
PORT = "5000"
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://icyizere-v2-production.up.railway.app"
