[services.backend]
name = "backend"
buildCommand = "cd server && npm install && npm run build"
startCommand = "cd server && npm start"
env = [
  "MONGO_URI",
  "JWT_SECRET",
  "PORT",
  "NODE_ENV",
  "JWT_EXPIRE"
]

[services.frontend]
name = "frontend"
buildCommand = "cd client && npm install && npm run build"
startCommand = "cd client && npm start"
env = [
  "NEXT_PUBLIC_API_URL"
]

[env]
MONGO_URI = "mongodb+srv://diope2diope:3IpTZ6hGwXkEdgm7@cluster0.poyyb0c.mongodb.net/icyizere?retryWrites=true&w=majority"
JWT_SECRET = "your_jwt_secret_key_here"
JWT_EXPIRE = "30d"
PORT = "5000"
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://icyizere-v2-production.up.railway.app"
